# Generated by Django 5.2.4 on 2025-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tododb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('task', models.CharField(max_length=4096)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
